"""empty message

Revision ID: 0116f72aba5d
Revises: 60f36dbe74f5
Create Date: 2022-08-20 16:24:18.322049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0116f72aba5d'
down_revision = '60f36dbe74f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'planets', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'planets', type_='unique')
    # ### end Alembic commands ###
